---
global:
  pattern: multicloud-gitops
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Automatic
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
namespaces:
  - devapp2
projects:
  - devapp2
applications:
  devapp2:
    name: devapp2
    namespace: devapp2
    project: devapp2
    repoURL: https://github.com/jstrahle/sample-app.git
    path: charts/sample-app
    targetRevision: main
