apiVersion: v1
kind: ServiceAccount
metadata:
  name: subscription-patcher
  namespace: ack-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: patch-subscription
  namespace: ack-system
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["subscriptions"]
    verbs: ["get", "patch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: patch-subscription-binding
  namespace: ack-system
subjects:
  - kind: ServiceAccount
    name: subscription-patcher
    namespace: ack-system
roleRef:
  kind: Role
  name: patch-subscription
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-installplanapproval
  namespace: ack-system
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: subscription-patcher
      containers:
        - name: patch
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Patching Subscription to Manual..."
              kubectl patch subs ack-s3-controller \
                -n ack-system \
                --type=merge \
                -p '{"spec": {"installPlanApproval": "Manual"}}'
      restartPolicy: Never
